import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
} from "../assets/images/index";
import { adminAxiosInstance } from "../redux/constants/AxiosInstance";

// // =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "whishlist",
    link: "/wishList",
  },
];
// // =================== NavBarList End here ======================
// // =================== Special Offer data Start here ============
export const SplOfferData = [

  {
    _id: 1001,
    name: "Cap for Boys",
    category: "Accessories",
    currentPrice: "35.00",
    regularPrice: "50.00",
    description: "A stylish cap for boys, perfect for casual wear.",
    images: ["spfOne"],
    status: "Available",
    stock: [{ quantity: 30, size: "M" }, { quantity: 20, size: "L" }],
    createdAt: "2024-06-01",
  },
  {
    _id: 1002,
    name: "Tea Table",
    category: "Furniture",
    currentPrice: "180.00",
    regularPrice: "200.00",
    description: "A modern tea table for your living room.",
    images: ["spfTwo"],
    status: "Available",
    stock: [{ quantity: 15, size: "Standard" }],
    createdAt: "2024-06-02",
  },
  {
    _id: 1003,
    name: "Headphones",
    category: "Electronics",
    currentPrice: "25.00",
    regularPrice: "35.00",
    description: "High-quality headphones with noise cancellation.",
    images: ["spfThree"],
    status: "Out of Stock",
    stock: [{ quantity: 0, size: "One Size" }],
    createdAt: "2024-06-03",
  },
  {
    _id: 1004,
    name: "Sun Glasses",
    category: "Accessories",
    currentPrice: "220.00",
    regularPrice: "250.00",
    description: "Stylish sunglasses with UV protection.",
    images: ["spfFour"],
    status: "Available",
    stock: [{ quantity: 25, size: "One Size" }],
    createdAt: "2024-06-04",
  },
  {
    _id: 1005,
    name: "Flower Base",
    category: "Home Decor",
    currentPrice: "35.00",
    regularPrice: "45.00",
    description: "Elegant flower base for your living space.",
    images: ["bestSellerOne"],
    status: "Available",
    stock: [{ quantity: 30, size: "Medium" }, { quantity: 10, size: "Large" }],
    createdAt: "2024-06-05",
  },
  {
    _id: 1006,
    name: "New Backpack",
    category: "Bags",
    currentPrice: "180.00",
    regularPrice: "220.00",
    description: "Durable and spacious backpack for travel.",
    images: ["bestSellerTwo"],
    status: "Available",
    stock: [{ quantity: 40, size: "Standard" }],
    createdAt: "2024-06-06",
  },
  {
    _id: 1007,
    name: "Household Materials",
    category: "Home Essentials",
    currentPrice: "25.00",
    regularPrice: "30.00",
    description: "Essential items for everyday household use.",
    images: ["bestSellerThree"],
    status: "Available",
    stock: [{ quantity: 50, size: "Pack" }],
    createdAt: "2024-06-07",
  },
  {
    _id: 1008,
    name: "Travel Bag",
    category: "Bags",
    currentPrice: "220.00",
    regularPrice: "250.00",
    description: "Sturdy travel bag for all your journeys.",
    images: ["bestSellerFour"],
    status: "Available",
    stock: [{ quantity: 20, size: "Large" }],
    createdAt: "2024-06-08",
  },
  {
    _id: 1009,
    name: "Round Table Clock",
    category: "Home Decor",
    currentPrice: "44.00",
    regularPrice: "55.00",
    description: "Classic round table clock for home and office.",
    images: ["newArrOne"],
    status: "Available",
    stock: [{ quantity: 25, size: "Small" }],
    createdAt: "2024-06-09",
  },
  {
    _id: 1010,
    name: "Smart Watch",
    category: "Electronics",
    currentPrice: "250.00",
    regularPrice: "300.00",
    description: "Smartwatch with fitness tracking features.",
    images: ["newArrTwo"],
    status: "Available",
    stock: [{ quantity: 15, size: "One Size" }],
    createdAt: "2024-06-10",
  },
  // Additional Items can be added similarly
];

// ];
// // =================== Special Offer data End here ==============

// // =================== PaginationItems Start here ===============


export const paginationItems = [
  {
    _id: 1001,
    name: "Cap for Boys",
    category: "Accessories",
    currentPrice: "35.00",
    regularPrice: "50.00",
    description: "A stylish cap for boys, perfect for casual wear.",
    images: ["spfOne"],
    status: "Available",
    stock: [{ quantity: 30, size: "M" }, { quantity: 20, size: "L" }],
    createdAt: "2024-06-01",
  },
  {
    _id: 1002,
    name: "Tea Table",
    category: "Furniture",
    currentPrice: "180.00",
    regularPrice: "200.00",
    description: "A modern tea table for your living room.",
    images: ["spfTwo"],
    status: "Available",
    stock: [{ quantity: 15, size: "Standard" }],
    createdAt: "2024-06-02",
  },
  {
    _id: 1003,
    name: "Headphones",
    category: "Electronics",
    currentPrice: "25.00",
    regularPrice: "35.00",
    description: "High-quality headphones with noise cancellation.",
    images: ["spfThree"],
    status: "Out of Stock",
    stock: [{ quantity: 0, size: "One Size" }],
    createdAt: "2024-06-03",
  },
  {
    _id: 1004,
    name: "Sun Glasses",
    category: "Accessories",
    currentPrice: "220.00",
    regularPrice: "250.00",
    description: "Stylish sunglasses with UV protection.",
    images: ["spfFour"],
    status: "Available",
    stock: [{ quantity: 25, size: "One Size" }],
    createdAt: "2024-06-04",
  },
  {
    _id: 1005,
    name: "Flower Base",
    category: "Home Decor",
    currentPrice: "35.00",
    regularPrice: "45.00",
    description: "Elegant flower base for your living space.",
    images: ["bestSellerOne"],
    status: "Available",
    stock: [{ quantity: 30, size: "Medium" }, { quantity: 10, size: "Large" }],
    createdAt: "2024-06-05",
  },
  {
    _id: 1006,
    name: "New Backpack",
    category: "Bags",
    currentPrice: "180.00",
    regularPrice: "220.00",
    description: "Durable and spacious backpack for travel.",
    images: ["bestSellerTwo"],
    status: "Available",
    stock: [{ quantity: 40, size: "Standard" }],
    createdAt: "2024-06-06",
  },
  {
    _id: 1007,
    name: "Household Materials",
    category: "Home Essentials",
    currentPrice: "25.00",
    regularPrice: "30.00",
    description: "Essential items for everyday household use.",
    images: ["bestSellerThree"],
    status: "Available",
    stock: [{ quantity: 50, size: "Pack" }],
    createdAt: "2024-06-07",
  },
  {
    _id: 1008,
    name: "Travel Bag",
    category: "Bags",
    currentPrice: "220.00",
    regularPrice: "250.00",
    description: "Sturdy travel bag for all your journeys.",
    images: ["bestSellerFour"],
    status: "Available",
    stock: [{ quantity: 20, size: "Large" }],
    createdAt: "2024-06-08",
  },
  {
    _id: 1009,
    name: "Round Table Clock",
    category: "Home Decor",
    currentPrice: "44.00",
    regularPrice: "55.00",
    description: "Classic round table clock for home and office.",
    images: ["newArrOne"],
    status: "Available",
    stock: [{ quantity: 25, size: "Small" }],
    createdAt: "2024-06-09",
  },
  {
    _id: 1010,
    name: "Smart Watch",
    category: "Electronics",
    currentPrice: "250.00",
    regularPrice: "300.00",
    description: "Smartwatch with fitness tracking features.",
    images: ["newArrTwo"],
    status: "Available",
    stock: [{ quantity: 15, size: "One Size" }],
    createdAt: "2024-06-10",
  },
  // Additional Items can be added similarly
];

// // =================== PaginationItems End here =================
